name: CI/CD

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master

# Prevent multiple deployments from running simultaneously
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
    - run: yarn
    - run: yarn lint
  compilation-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
    - run: yarn
    - run: yarn build

  deploy-master:
    runs-on: ubuntu-latest
    needs: [lint, compilation-tests]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: beta-emeralddb
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}

  deploy-release:
    runs-on: ubuntu-latest
    needs: [lint, compilation-tests]
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: emeralddb
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
